### ISSUE TITLE
Download page is not working

### ISSUE THREAD

**Issue by CalvinRossSmith** [mavit/deluge-trafficlimits#6]
https://www.mavit.org.uk/deluge-trafficlimits/ it says the application is not available

**Comment by mavit** [comment]
I need to get around to arranging some replacement website hosting.  In the meantime, it should be possible to build from source by cloning this repository and following the instructions in the INSTALL file.

**Comment by Tsaukpaetra** [comment]
GitHub can host your release package, right? I don't know if that needs money or not though...
